server:
  port: 8888

spring:

  devtools:
      restart:
        #热部署开关
        enabled: true

  profiles:
      active: druid
#数据源配置
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      druid:
          url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
          username: root
          password: 123qwe
          # 初始连接数
          initial-size: 10
          # 最大连接池数量
          max-active: 100
          # 最小连接池数量
          min-idle: 10
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
              enabled: true
#                url-pattern: /monitor/druid/*
          filter:
              stat:
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: false
              wall:
                  config:
                      multi-statement-allow: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/hrms?characterEncoding=UTF-8
#    username: root
#    password: 123qwe
#    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapperLocations: classpath:mapper/*.xml

# MyBatis
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
shiro:
  user:
    # 登录地址
    loginUrl: /login
